name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
        sudo dpkg -i cuda-keyring_1.0-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-11-8

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          build-essential \
          gcc-10 \
          g++-10

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
          -G Ninja

    - name: Build
      run: |
        cd build
        ninja

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Test CLI help
      run: |
        cd build
        ./janus-sim --help | grep -q "Janus P3M"

  build-cpu-only:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          build-essential \
          gcc-10 \
          g++-10

    - name: Configure CMake (CPU-only)
      run: |
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -G Ninja

    - name: Build (CPU-only)
      run: |
        cd build
        ninja

    - name: Run tests (CPU-only)
      run: |
        cd build
        ctest --output-on-failure

    - name: Test CLI help (CPU-only)
      run: |
        cd build
        ./janus-sim --help | grep -q "Janus P3M"

  build-with-options:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
        sudo dpkg -i cuda-keyring_1.0-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-11-8

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          build-essential \
          gcc-10 \
          g++-10

    - name: Configure CMake with options
      run: |
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
          -DJANUS_FAST_MATH=ON \
          -DJANUS_DETERMINISTIC=OFF \
          -G Ninja

    - name: Build with options
      run: |
        cd build
        ninja

    - name: Run tests with options
      run: |
        cd build
        ctest --output-on-failure